version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

formats: []

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs