[project]
name = "matrix-py"
author = "Tom-the-Bomb"
description = "A multipurpose discord bot featuring mainly Image Manipulation & Games and more"
license = {file = "LICENSE"}
requires-python = ">=3.10"

[tool.pyright]
typeCheckingMode = "strict"